/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Knob: typeof import('./src/components/Knob.vue')['default']
    KnobGroup: typeof import('./src/components/KnobGroup.vue')['default']
    LividOhmRGB: typeof import('./src/components/Controllers/LividOhmRGB.vue')['default']
    LividOhmRGBGridOnly: typeof import('./src/components/Controllers/LividOhmRGBGridOnly.vue')['default']
    MultiController: typeof import('./src/components/Controllers/MultiController.vue')['default']
    MultiControllerSmall: typeof import('./src/components/Controllers/MultiControllerSmall.vue')['default']
    NuxtLogo: typeof import('./src/components/NuxtLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    SliderGroup: typeof import('./src/components/SliderGroup.vue')['default']
  }
}
